# .github/workflows/molit.yml
name: molit-press-bot
on:
  schedule:
    - cron: "0 9 * * *"  # 매일 18:00 KST
  workflow_dispatch: {}   # <- 수동 실행 버튼

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Test ping (optional)
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python - <<'PY'
          import os, requests
          t=os.environ['BOT_TOKEN']; c=os.environ['CHAT_ID']
          requests.post(f"https://api.telegram.org/bot{t}/sendMessage",
                        data={"chat_id": c, "text": "🔔 테스트: Actions에서 발송합니다"})
          PY
      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python .github/workflows/molit_bot_now.py
